Repository Matrimania/matrimania-client, pull requests merged in 2021-01, with the labels that each got.

#22 Setup environment
  .eslintcache
  README.md
  node_modules/.cache/babel-loader/66234be1b6670840580df59956b87d42.json
  node_modules/.cache/babel-loader/9bac62290b1e3a3da5b0010b1075c38c.json
  node_modules/.cache/babel-loader/9c80bc3fdaaf1abb2d53e87ab96ab03b.json
  node_modules/.cache/babel-loader/aee8aca9b3edb5059e232d4b135fedaa.json
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.test.js
  src/App.tsx
  src/index.css
  src/logo.svg
  src/react-app-env.d.ts
  tsconfig.json
Labels: Check-In #2, Priority #1, documentation

#34 Wedding details eb
  .vscode/settings.json
  src/components/App/App.tsx
  src/components/VenderDashboard/VenderDashboard.tsx
  src/components/WeddingCard/WeddingCard.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
  src/components/WeddingPhotoList/WeddingPhotoList.tsx
Labels: Client, Priority #1

#38 Control form: Guest List
  src/components/App/App.tsx
  src/components/Guest/Guest.tsx
  src/components/GuestList/GuestList.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
Labels: Check-In #3, FE, Priority #1, Vendor, enhancement

#47 Wedding details update eb
  src/components/WeddingDetails/WeddingDetails.tsx
  src/weddingData.tsx
Labels: Client, FE, Priority #1, enhancement

#52 Wedding details styling km
  src/assets/emptyGuestList.png
  src/components/App/styledComponents.styles.ts
  src/components/Guest/Guest.css
  src/components/Guest/Guest.tsx
  src/components/GuestList/GuestList.css
  src/components/GuestList/GuestList.tsx
  src/components/VenderDashboard/VenderDashboard.css
  src/components/VenderDashboard/VenderDashboard.tsx
  src/components/WeddingCard/WeddingCard.css
  src/components/WeddingCard/WeddingCard.tsx
  src/components/WeddingDetails/WeddingDetails.css
  src/components/WeddingDetails/WeddingDetails.tsx
Labels: Author Things Ready To Merge, Check-In #4, Priority #1, Vendor, enhancement, styling

#54 Control form error handling eb
  src/components/Guest/Guest.tsx
  src/components/GuestList/GuestList.tsx
  src/weddingData.tsx
Labels: Client, FE, enhancement

#56 Wedding endpoints km
  src/apiCalls.tsx
  src/components/AddWeddingForm/AddWeddingForm.css
  src/components/AddWeddingForm/AddWeddingForm.tsx
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/VenderDashboard/VenderDashboard.tsx
  src/components/WeddingCard/WeddingCard.tsx
  src/components/WeddingPhotoList/WeddingPhotoList.css
  src/components/WeddingPhotoList/WeddingPhotoList.tsx
Labels: Author Things Ready To Merge, Check-In #4, FE, Priority #1, Vendor, enhancement

#69 Edit Photo List View
  package-lock.json
  public/index.html
  public/manifest.json
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/GuestList/GuestList.tsx
  src/components/Photo/Photo.tsx
  src/components/PhotoListForm/PhotoListForm.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
  src/components/WeddingPhotoList/WeddingPhotoList.tsx
Labels: Check-In #4, FE, Priority #1, enhancement

#87 PhotoListForm Updates
  src/components/App/styledComponents.styles.ts
  src/components/Checkbox/Checkbox.css
  src/components/Checkbox/Checkbox.tsx
  src/components/GuestList/GuestList.tsx
  src/components/Photo/Photo.css
  src/components/Photo/Photo.tsx
  src/components/PhotoListForm/PhotoListForm.css
  src/components/PhotoListForm/PhotoListForm.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
  src/components/WeddingPhotoList/WeddingPhotoList.css
  src/components/WeddingPhotoList/WeddingPhotoList.tsx
Labels: FE, enhancement, styling

#94 Testing eb
  src/__tests__/Checkbox.test.tsx
  src/__tests__/Guest.test.tsx
  src/__tests__/GuestList.test.tsx
  src/__tests__/Photo.test.tsx
  src/__tests__/PhotoListForm.test.tsx
  src/__tests__/VendorDashboard.test.tsx
  src/__tests__/WeddingCard.test.tsx
  src/__tests__/WeddingDetails.test.tsx
  src/__tests__/WeddingPhotoList.test.tsx
  src/components/GuestList/GuestList.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
  src/components/WeddingPhotoList/WeddingPhotoList.tsx
Labels: Author Adds Line Comments, Client, FE, Priority #1, Testing

#100 Async functionality km
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/VendorDashboard/VendorDashboard.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
  src/components/WeddingPhotoList/WeddingPhotoList.tsx
Labels: Author Things Ready To Merge, BUG!, Check-In #4, FE, Priority #1, Vendor, enhancement

#107 Refactor tests eb
  src/__tests__/GuestList.test.tsx
  src/__tests__/Photo.test.tsx
  src/__tests__/PhotoListForm.test.tsx
  src/__tests__/VendorDashboard.test.tsx
  src/__tests__/WeddingCard.test.tsx
  src/__tests__/WeddingDetails.test.tsx
  src/__tests__/WeddingPhotoList.test.tsx
  src/components/WeddingCard/WeddingCard.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
Labels: Author Things Ready To Merge, FE, Testing

#109 Refactor tests eb
  src/__tests__/WeddingDetails.test.tsx
  src/components/Photo/Photo.tsx
  src/components/WeddingPhotoList/WeddingPhotoList.tsx
  src/index.tsx
Labels: Author Things Ready To Merge, FE

#111 Bug fixes km
  src/apiCalls.tsx
  src/assets/NoWeddings.png
  src/components/AddWeddingForm/AddWeddingForm.tsx
  src/components/App/App.tsx
  src/components/App/styledComponents.styles.ts
  src/components/GuestList/GuestList.tsx
  src/components/PhotoListForm/PhotoListForm.tsx
  src/components/VendorDashboard/VendorDashboard.css
  src/components/VendorDashboard/VendorDashboard.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
Labels: Author Things Ready To Merge, FE, Priority #2, Vendor, enhancement, styling

#118 Bug fix eb
  src/components/AddWeddingForm/AddWeddingForm.tsx
  src/components/App/App.tsx
Labels: FE, Vendor

#120 Error handling km
  public/favicon.ico
  public/index.html
  src/assets/EmptyPhoto.png
  src/assets/NoCurrent.png
  src/assets/NoPast.png
  src/assets/NoUpcoming.png
  src/assets/NoWeddings.png
  src/assets/arrow.png
  src/assets/goodWork.png
  src/assets/loadingText.png
  src/assets/startShoot.png
  src/components/AddWeddingForm/AddWeddingForm.tsx
  src/components/App/App.tsx
  src/components/App/styledComponents.styles.ts
  src/components/GuestList/GuestList.tsx
  src/components/PhotoListForm/PhotoListForm.tsx
  src/components/PhotoShootView/PhotoShootView.css
  src/components/PhotoShootView/PhotoShootView.tsx
  src/components/VendorDashboard/VendorDashboard.css
  src/components/VendorDashboard/VendorDashboard.tsx
Labels: Author Things Ready To Merge, FE, Priority #3, Vendor, styling

#124 Integration testing
  public/index.html
  src/__tests__/AddWeddingForm.test.tsx
  src/__tests__/App.test.tsx
  src/apiCalls.tsx
  src/components/AddWeddingForm/AddWeddingForm.tsx
  src/components/App/App.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/GuestList/GuestList.tsx
  src/components/PhotoListForm/PhotoListForm.tsx
  src/components/WeddingCard/WeddingCard.tsx
  src/components/WeddingDetails/WeddingDetails.tsx
Labels: BUG!, Testing, enhancement
